language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install mock pytest pytest-cov "coverage>4.0,<4.4" codeclimate-test-reporter
  - python setup.py -q install

script:
  - py.test --cov=module tests
  - codeclimate-test-reporter --file .coverage
