language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - py.test --cov=module tests
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then coverage xml; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then codeclimate-test-reporter --file .coverage; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python-codacy-coverage -r coverage.xml; fi'
